name: CI Pipeline

on:
  workflow_call

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Cache pip and pipenv caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pipenv
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies with pipenv
        run: pipenv install --dev

      - name: Run pytest with coverage
        run: pipenv run pytest --cov=app --cov-report=xml --cov-report=term-missing

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true

  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Cache pip and pipenv caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pipenv
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies with pipenv
        run: pipenv install --dev

      - name: Run formatting check
        run: pipenv run black --check .

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pipenv
        run: pip install pipenv

      - name: Cache pip and pipenv caches
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.cache/pipenv
          key: ${{ runner.os }}-pip-${{ hashFiles('Pipfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies with pipenv
        run: pipenv install --dev

      - name: Run linting
        run: pipenv run flake8 .
